apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
        - name: backend-server
          image: your-backend-server-image:tag
          ports:
            - containerPort: 3000
